fix: IdlAccountsCollection included
metaplex-foundation/solita pull request #81
Opened 2022-09-02 09:11 UTC by ricardocr987

https://github.com/metaplex-foundation/solita/issues/78
Now this case of IDL is taken into account.

The problem you said in the issue is solved (A instruction should just have a list of accounts, each of type AccountMetadata (not arrays or anything else), but not 100% sure if it is the best way, as I included in the code as a commentary:

as there are cases where the collection of the accounts is reused on the same ix, is needed to change the name of the account (because in that case would be accounts in the same instruction with the same name)

To solve that, I have included on the accounts the name of the list of the accounts.

This case appears on the IDL of Marinade Finance, Jet Protocol and Jupiter, so would be great to fix.

2022-09-02 23:21 UTC, thlorenz requested changes
Thanks for the work!

> This case appears on the IDL of Marinade Finance, Jet Protocol and Jupiter, so would be great to fix.

What tool is used to generate IDLs for those? Is there a spec for this accounts collection type in the IDL somewhere?

The solution you provide is interesting, but seems to be a somewhat _hacky_ work-around an issue that should be solved elsewhere at least when it comes to the _fix_ of possible account name clashes.

I would like to understand more about why tools generate such nested accounts.
However in the meantime please address the nits I pointed out.

2022-09-02 23:21 UTC, thlorenz commented on src/render-instruction.ts
> +      else {
Please follow code standards here and/or run `yarn lint:fix` (there is a `.prettierrc` in the root which your editor doesn't seem to respect).
The lint part of the workflow most likely will fail due to this.

2022-09-02 23:21 UTC, thlorenz commented on src/render-instruction.ts
> +        acc.accounts.map((ac) => {
If you're not assigning the result of `map` then you should use `forEach` instead.

But I prefer `for (const acc of acc.accounts)`.

2022-09-02 23:21 UTC, thlorenz commented on src/render-instruction.ts
> +          ac.name += acc.name.charAt(0).toUpperCase().concat(acc.name.slice(1))
I'm not a huge fan of this, what if there is an account that has the same name but with uppercase, i.e. `Accounts`?
Seems to be somewhat of a hack to me and I don't understand fully why the name as to be changed.

It seems to me the tool generating the IDL should choose a name instead that is less likely to clash, i.e.`__accounts__`.

At any rate all the data read from the IDL should be considered immutable as it is processed in other places as well and it is super hard to track down issues if it is mutated in multiple places.
If you look through the code base (aside from fixing some anchor issues) we never mutate any data read from the IDL, but derive other data from it in a readonly fashion instead.

2022-09-02 23:21 UTC, thlorenz commented on src/render-instruction.ts
> +    this.ix.accounts.map((acc: IdlInstructionAccount | IdlAccountsCollection) => {
If you're not assigning the result of `map` then you should use `forEach` instead. (previously the result of this was returned).

But I prefer `for (const acc of this.ix.accounts)`.

2022-09-02 23:21 UTC, thlorenz commented on src/render-instruction.ts
> +        else{
ditto above

2022-09-06 08:10 UTC, ricardocr987 commented
I understand that the IDL of these programs is built with Anchor. Marinade and Jet are published here (https://www.apr.dev/) "Anchor Program Registry".

Where else could this problem be solved?

In the end you don't care about the collection of accounts itself, the important thing is the list of all the accounts used in the context of an instruction.

About the name collision, it is something that the only solution I see is with the modification I have made, if you consider another way is better, I would be happy to include it.

A check could be made to check if in this collection case account names are repeated (by using the same struct/same collection of accounts twice within the context as in the case of Jet with DexMarketAccounts):

https://github.com/jet-lab/jet-v1/blob/master/programs/jet/src/instructions/liquidate_dex.rs#L759

In this case it would be necessary to modify the name of the accounts, no doubt, because will be duplicated account names.

2022-09-06 22:51 UTC, thlorenz commented
> About the name collision, it is something that the only solution I see is with the modification I have made, if you consider another way is better, I would be happy to include it.

I'll have a look on how to improve it.

But first you please fix the lint errors in the meantime and add an [integration test here](https://github.com/metaplex-foundation/solita/blob/master/test/integration/features.ts)?
Basically provide a sample IDL and make sure that the generated code is valid via that test.

That would also allow me to understand better what your changes are doing and possibly modify them without breaking anything.

2022-09-08 18:11 UTC, thlorenz commented on test/integration/features.ts
> +// -----------------
Looks like you forgot to change the comment here.

2022-09-08 18:15 UTC, thlorenz commented
Thanks for the update .. CI is now passing ..
Please fix the one nit I pointed out and I'll have a look to see how to workaround the parts I didn't like to get this feature in.

2022-09-19 15:15 UTC, thlorenz commented
Thanks for fixing .. I'll have a look this week (was OOO last) to get this adapted + merged ASAP.

2022-09-22 17:14 UTC, thlorenz commented
Just FYI I'm currently working on cleaning this up to get it merged properly.
Since I cannot push to your branch I'm doing this [over here](https://github.com/metaplex-foundation/solita/tree/thlorenz/pr/72)

I'll create a separate PR once that is done and will give you a chance to give feedback before merging.

2022-09-22 17:55 UTC, thlorenz commented
@ricardocr987 please review https://github.com/metaplex-foundation/solita/pull/87 and we can merge if the changes I made are fine with you.

2022-09-26 03:46 UTC, thlorenz commented
Superseeded by #87

2022-09-26 03:46 UTC, closed without merging